### ISSUE TITLE
[NEOS-381] make system transformers an enum in proto so they're statically typed

### ISSUE THREAD

**Issue by evisdrenova** [nucleuscloud/neosync#782]
<sub>From [SyncLinear.com](https://synclinear.com) | [NEOS-381](https://linear.app/nucleus-cloud/issue/NEOS-381/make-system-transformers-an-enum-in-proto-so-theyre-statically-typed)</sub>

**Comment by evisdrenova** [comment]
Hey @sibis thanks for wanting to contribute and sorry for the delay in getting back to you! 

Yes, we want to make the system transformers into an enum so that they're typed. We have sections in our codebase where we are hardcoding a system transformer and we want to type those fields. For example, [here](https://github.com/nucleuscloud/neosync/blob/main/worker/pkg/workflows/datasync/activities/activities.go#L570),
```

	for _, col := range cols {
		if col.Transformer != nil && col.Transformer.Source != "" && col.Transformer.Source != "passthrough" && col.Transformer.Source != "generate_default" {

```

we want to update this:

```
col.Transformer.Source != "passthrough"
```

to something like:

```
col.Transformer.Source != systemTransformer.Passthrough
```

There are a few other instances (particularly in our tests) where this occurs. I think the majority of them will be the "Passthrough" transformer but there could be others as well. 

@nickzelei anything else to add in here?

**Comment by nickzelei** [comment]
Hi @sibis - sorry I missed this thread here.

I think the property is called `source` now, for the jobmappingtransformer message
https://github.com/nucleuscloud/neosync/blob/main/backend/protos/mgmt/v1alpha1/job.proto#L131

This is just a string, but my thinking is that it can be made into a proto enum.

This (at least today) corresponds 1:1 with the source key for `SystemTransformer` https://github.com/nucleuscloud/neosync/blob/main/backend/protos/mgmt/v1alpha1/transformer.proto#L82

The worker process that processes the transformers when it turns them into a sync config uses a big switch statement and cases off of those string values:
https://github.com/nucleuscloud/neosync/blob/main/worker/pkg/workflows/datasync/activities/activities.go#L624

Ideally, I'd like this to be more statically typed instead of just strings so that we're not passing around string values everywhere.

If the JobMappingTransformer is user defined (meaning: custom) the source is `custom` today.

**Comment by nickzelei** [comment]
Awesome! Will check it out.
